// Adapted from the owner's working StudioArtifactPreview.astro; no renderer dependencies.
import { useId, useRef, useState } from 'react';
import styles from './website-artifacts.module.css';
const feedback = [
 { title: 'Export to CSV is missing columns', from: 'Maya Chen', source: 'Email', priority: 'High', status: 'New' },
 { title: 'Dark mode makes status badges hard to read', from: 'Luis Ortega', source: 'Chat', priority: 'Medium', status: 'Triaged' },
 { title: 'Let me bulk-assign items to a teammate', from: 'Priya Nair', source: 'Interview', priority: 'High', status: 'New' },
];
export function WebsiteArtifactPreview({ kind }: { kind: 'view' | 'diagram' | 'canvas' | 'document' }) {
 const root = useRef<HTMLDivElement>(null);
 const arrowId = useId().replaceAll(':', '') + '-arrow';
 const [items, setItems] = useState(feedback);
 const [filter, setFilter] = useState('all');
 const [announcement, setAnnouncement] = useState('');
 function toggleItem(index: number) {
  const item = items[index]; const status = item.status === 'New' ? 'Triaged' : 'New';
  setItems(items.map((entry, i) => i === index ? {...entry, status} : entry));
  setAnnouncement(item.title + ' marked as ' + status.toLowerCase() + '.');
  if (filter !== 'all' && status.toLowerCase() !== filter) root.current?.querySelector<HTMLButtonElement>('button[aria-pressed="true"]')?.focus();
 }
 return (<div className={styles['artifact-stage']}>
  <div className={styles['artifact-file']}><span className={styles['file-dot']} aria-hidden="true"></span><span>{kind === 'view' ? 'feedback-inbox.tsx' : kind === 'diagram' ? 'triage-flow.mermaid' : kind === 'canvas' ? 'explorations.excalidraw' : 'context.md'}</span><span className={styles['file-type']}>{kind === 'view' ? 'Working view' : kind === 'diagram' ? 'Flow diagram' : kind === 'canvas' ? 'Exploration canvas' : 'Design context'}</span></div>
  {kind === 'view' && <div className={styles['feedback-view']} ref={root}>
    <div className={styles['feedback-heading']}><div><h4>Feedback inbox</h4></div><svg className={styles['feedback-mark']} viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="M8 10h32v25H25l-9 7v-7H8V10Zm8 8h16M16 25h10" stroke="currentColor" strokeWidth="1.5"/></svg></div>
    <p className={styles['feedback-intro']}>Everything customers have told us, and what needs attention.</p>
    <div className={styles['feedback-filters']} role="group" aria-label="Filter feedback"><button type="button" aria-pressed={filter === "all"} onClick={() => setFilter("all")}>All feedback <span>3</span></button><button type="button" aria-pressed={filter === "new"} onClick={() => setFilter("new")}>New <span>{items.filter(item => item.status === "New").length}</span></button><button type="button" aria-pressed={filter === "triaged"} onClick={() => setFilter("triaged")}>Triaged <span>{items.filter(item => item.status === "Triaged").length}</span></button></div>
    <div className={styles['feedback-columns']} aria-hidden="true"><span>Feedback</span><span>Priority</span><span>Status</span></div>
    <div className={styles['feedback-list']}>{items.map((item, index) => <article key={item.title} hidden={filter !== "all" && item.status.toLowerCase() !== filter} className={styles['feedback-item']} data-feedback-item data-status={item.status.toLowerCase()}><div className={styles['feedback-item-text']}><h5>{item.title}</h5><p>{item.from} · {item.source}</p></div><span className={`${styles["feedback-priority"]} ${item.priority === "High" ? styles["priority-high"] : ""}`}>{item.priority}</span><button type="button" className={styles['feedback-status']} onClick={() => toggleItem(index)} aria-label={`Mark ${item.title} as ${item.status === 'New' ? 'triaged' : 'new'}`}>{item.status}</button></article>)}</div>
    <p className={styles['feedback-empty']} hidden={items.some(item => filter === "all" || item.status.toLowerCase() === filter)}>No feedback in this status.</p>
    <p className={styles['announcement']} role="status" aria-live="polite">{announcement}</p>
  </div>}
  {kind === 'diagram' && <div className={styles['diagram-view']}><h4>Give every request a direction.</h4><svg className={styles['flow-drawing']} viewBox="0 0 640 340" role="img" aria-label="Capture feedback, review its priority, then plan it or keep it for later. Later requests return for review."><defs><marker id={arrowId} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="m1 1 8 4-8 4" fill="none" stroke="currentColor" strokeWidth="1.5"/></marker></defs><g className={styles['flow-lines']} markerEnd={`url(#${arrowId})`}><path d="M167 160H230"/><path d="M356 160H392V86H474"/><path d="M356 160H392V234H474"/><path d="M545 258V310H293V212"/></g><g className={styles['flow-nodes']}><rect x="34" y="136" width="133" height="48" rx="6"/><path d="m230 160 63-52 63 52-63 52-63-52Z"/><rect x="474" y="62" width="142" height="48" rx="6"/><rect x="474" y="210" width="142" height="48" rx="6"/></g><g className={styles['flow-labels']}><text x="100" y="165">Capture feedback</text><text x="293" y="165">Review priority</text><text x="545" y="91">Plan next step</text><text x="545" y="239">Keep for later</text></g><g className={styles['flow-annotations']}><text x="433" y="72" textAnchor="middle">Act now</text><text x="433" y="220" textAnchor="middle">Not yet</text><text x="419" y="296" textAnchor="middle">Revisit as needs change</text></g></svg><ol className={styles['mobile-flow']} aria-label="Feedback triage flow"><li>Capture feedback</li><li>Review priority</li><li><span>Plan next step</span><span>Keep for later</span></li></ol><p className={styles['mobile-flow-return']}>Revisit deferred requests as customer needs change.</p></div>}
  {kind === 'canvas' && <div className={styles['canvas-view']}><div className={styles['canvas-note']}><p className={styles['small-note']}>A direction to explore</p><h4>Less backlog.<br />More clarity.</h4><p>Help product teams see what matters and decide what to do next.</p></div><div className={styles['canvas-sketch']}><span className={styles['sketch-label']}>Triage workspace</span><div className={styles['sketch-top']}></div><div className={styles['sketch-tabs']}><i></i><i></i><i></i></div>{[1,2,3].map(row => <div key={row} className={styles['sketch-row']}><span></span><div><i></i><i></i></div><b>◇</b></div>)}</div><div className={styles['canvas-question']}><span>What if…</span><p>Every piece of feedback had a clear next step?</p></div><svg className={styles['canvas-connection']} viewBox="0 0 600 360" preserveAspectRatio="none" aria-hidden="true"><path d="M215 125C280 125 270 95 340 95M430 235C430 300 300 310 245 285" stroke="currentColor" strokeWidth="1.2" strokeDasharray="4 5" fill="none"/></svg></div>}
  {kind === 'document' && <div className={styles['document-view']}><h4>Turn feedback into decisions.</h4><p className={styles['document-intro']}>Give product teams a shared place to review customer requests, weigh their impact, and decide what comes next.</p><div className={styles['document-section']}><h5>What matters</h5><ul><li>Keep the customer's source visible.</li><li>Show priority and status at a glance.</li><li>Make triage a simple action in the inbox.</li></ul></div><div className={styles['document-decision']}><span className={styles['small-note']}>Design decision</span><p>Keep priority separate from status. A high-impact request may still need investigation before it belongs in the plan.</p></div><p className={styles['document-link']}>Related artifacts <span>feedback-inbox.tsx · triage-flow.mermaid</span></p></div>}
</div>);
}
